#!/usr/bin/env bash
set -euxo pipefail

TEMP_DIR="$(mktemp -d)"

APP_VERSION="26.616.32156"
curl -o "$TEMP_DIR/file.zip" "https://persistent.oaistatic.com/codex-app-prod/Codex-darwin-arm64-$APP_VERSION.zip"

HOSTED_CODEX_APP_ZIP="$TEMP_DIR/file.zip" bash ./scripts/prepare_asar

rm -rf "$TEMP_DIR"
